### ISSUE TITLE
Problem when I use data visualisation and postprocessing on Unix

### ISSUE THREAD

**Issue by JWDei** [magic-sph/magic#12]
When I use Data visualisation and postprocessing to try to run a sample on Unix, I meet a error that it made the sample stopped runing. To be precise, Python broke when running the case.
2018-11-16 14:07:48.195 Python[27926:1769878] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fa10ff1afd0
2018-11-16 14:07:48.198 Python[27926:1769878] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fa10ff1afd0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff446202db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff6b7d5c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff446b8db4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff44596820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff445961e8 _CF_forwarding_prep_0 + 120
	5   Tk                                  0x00007fff50cfe318 TkpInit + 467
	6   Tk                                  0x00007fff50c7d252 Tk_Init + 1710
	7   _tkinter.so                         0x00000001129e0bc4 Tcl_AppInit + 84
	8   _tkinter.so                         0x00000001129e058f Tkinter_Create + 1069
	9   Python                              0x0000000109d02ea6 PyEval_EvalFrameEx + 19200
	10  Python                              0x0000000109cfe18c PyEval_EvalCodeEx + 1540
	11  Python                              0x0000000109ca49cd function_call + 327
	12  Python                              0x0000000109c86de1 PyObject_Call + 97
	13  Python                              0x0000000109c916d0 instancemethod_call + 163
	14  Python                              0x0000000109c86de1 PyObject_Call + 97
	15  Python                              0x0000000109d06b28 PyEval_CallObjectWithKeywords + 159
	16  Python                              0x0000000109c8f9b0 PyInstance_New + 123
	17  Python                              0x0000000109c86de1 PyObject_Call + 97
	18  Python                              0x0000000109d02e90 PyEval_EvalFrameEx + 19178
	19  Python                              0x0000000109cfe18c PyEval_EvalCodeEx + 1540
	20  Python                              0x0000000109d071ed fast_function + 284
	21  Python                              0x0000000109d02d90 PyEval_EvalFrameEx + 18922
	22  Python                              0x0000000109cfe18c PyEval_EvalCodeEx + 1540
	23  Python                              0x0000000109ca49cd function_call + 327
	24  Python                              0x0000000109c86de1 PyObject_Call + 97
	25  Python                              0x0000000109d03767 PyEval_EvalFrameEx + 21441
	26  Python                              0x0000000109cfe18c PyEval_EvalCodeEx + 1540
	27  Python                              0x0000000109d071ed fast_function + 284
	28  Python                              0x0000000109d02d90 PyEval_EvalFrameEx + 18922
	29  Python                              0x0000000109d0718f fast_function + 190
	30  Python                              0x0000000109d02d90 PyEval_EvalFrameEx + 18922
	31  Python                              0x0000000109cfe18c PyEval_EvalCodeEx + 1540
	32  Python                              0x0000000109ca49cd function_call + 327
	33  Python                              0x0000000109c86de1 PyObject_Call + 97
	34  Python                              0x0000000109c916d0 instancemethod_call + 163
	35  Python                              0x0000000109c86de1 PyObject_Call + 97
	36  Python                              0x0000000109d06b28 PyEval_CallObjectWithKeywords + 159
	37  Python                              0x0000000109c8f9b0 PyInstance_New + 123
	38  Python                              0x0000000109c86de1 PyObject_Call + 97
	39  Python                              0x0000000109d02e90 PyEval_EvalFrameEx + 19178
	40  Python                              0x0000000109cfe18c PyEval_EvalCodeEx + 1540
	41  Python                              0x0000000109cfdb82 PyEval_EvalCode + 32
	42  Python                              0x0000000109d1f577 run_mod + 49
	43  Python                              0x0000000109d1f3b4 PyRun_InteractiveOneFlags + 344
	44  Python                              0x0000000109d1ee47 PyRun_InteractiveLoopFlags + 87
	45  Python                              0x0000000109d1ed5c PyRun_AnyFileExFlags + 60
	46  Python                              0x0000000109d30c10 Py_Main + 3136
	47  libdyld.dylib                       0x00007fff6c3ef015 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
I have tried it on multiple versions of the OS X, but I have been unable to solve the problem. Now my system is 10.13.6.

**Comment by tgastine** [comment]
It seems that your matplotlib install is not working. You should first try whether matplotlib is actually displaying plots as expected.

**Comment by JWDei** [comment]
I tested the matplotlib on my computer with an unrelated example, it does work.

**Comment by AnkitBarik** [comment]
Could you check if the file `magic.cfg` (in `$MAGIC_HOME/python/magic/`) has the following value set?

`backend=macosx`

The python autoconfig doesn't work properly on OSX, so the values in `magic.cfg` need to be set manually.

**Comment by JWDei** [comment]
> Could you check if the file `magic.cfg` (in `$MAGIC_HOME/python/magic/`) has the following value set?
> 
> `backend=macosx`
> 
> The python autoconfig doesn't work properly on OSX, so the values in `magic.cfg` need to be set manually.

It works! Thank you very much!
