### ISSUE TITLE
compilation failed with OpenMP

### ISSUE THREAD

**Issue by nschaeff** [magic-sph/magic#15]
Configure with: 
   ` cmake .. -DUSE_SHTNS=yes -DUSE_OMP=yes`
With gnu fortran 8.2.1 I get the following error when compiling:

[ 48%] Building Fortran object src/CMakeFiles/magic.exe.dir/get_nl.f90.o
/tmp/magic/src/get_nl.f90:461:0:

                if ( l_anel ) then
 
Erreur: « l_anel » non spécifié dans la région « parallel » englobante
/tmp/magic/src/get_nl.f90:460:0:

             do nPhi=1,n_phi_max
 
Erreur: région « parallel » englobante
make[2]: *** [src/CMakeFiles/magic.exe.dir/build.make:453: src/CMakeFiles/magic.exe.dir/get_nl.f90.o] Error 1
make[2]: *** Attente des tâches non terminées....
make[1]: *** [CMakeFiles/Makefile2:91: src/CMakeFiles/magic.exe.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by tgastine** [comment]
Regression fixed in 90d7c99
