### ISSUE TITLE
Segmentation fault happened when use axisymmetric shtns functions on KNL nodes 

### ISSUE THREAD

**Issue by alexisreboulsalze** [magic-sph/magic#17]
Some outputs (power, perpPar, TO, etc.) call shtns.axi_to_spat, shtns.spat_to_SH_axi and lead to a segmentation fault on KNL nodes.
I'm using the latest version of the code and the SHTNS 3.2.2 version compiled with the configuration command : 
./configure --enable-mkl --enable-knl --enable-magic-layout --prefix=$HOME/
Without these outputs, the code works well otherwise.

**Comment by tgastine** [comment]
This is an SHTns issue with the MagIC layout. Please clone the latest version on SHTns bitbucket repository it should work fine.

**Comment by alexisreboulsalze** [comment]
Thanks for the fast answer, it works now.
