### ISSUE TITLE
 Problem with 2D visualization with MPI

### ISSUE THREAD

**Issue by lakecity** [magic-sph/magic#18]
Hello! I have a problem with 2D visualization (1D works), Ubuntu 18.04. 
What I can do: 

i) without MPI and OpenMP I have plots produced from G*.TAG data files using greader_*so (buildLib = True) for the both precisions: 

from magic import *
gr = MagicGraph(ivar=1, tag='1',precision=np.float64) ....
either
s=Surf(precision=np.float64) ....

it's ok

ii) But with MPI and without OpenMP (with buildLib = True):

At line 39 of file readG_double.f90 (unit = 10, file = './G_1.1')
Fortran runtime error: I/O past end of record on unformatted file

If I understand it correctly the mpi header's lines 725--755 in out_graph_file.f90 do not correspond to 36 -- .. lines in readG_double.f90. The difference is additional write statements of the length.  Can you comment this?

iii) When the python's reader is used (with buildLib = False): then I have 

gr = MagicGraph(ivar=1, tag='1',precision=np.float64)

in fort_read(self, dt, shape, endian, order, head_size)
    318                          dtype=dt,
    319                          buffer=buf,
--> 320                          order=order)
    321         #fortran record ends with the header repeated. skip this.
    322         self.seek(head_size,1)

TypeError: buffer is too small for requested array

      2  n_r_max     =97,
      3  n_cheb_max  =95,
      4  n_phi_tot   =288,
      5 n_cheb_ic_max=15,

The result does not depend on MPI. And I have 128Hb shared memeory.

**Comment by AnkitBarik** [comment]
I confirmed this. In addition it seems to only happen with double precision output and numbered G files, and not time averaged G-files.

It's a bit puzzling since there is no difference between out_graph_file and readG for single and double precision other than the precision of the variables.

**Comment by tgastine** [comment]
In that case it might just mean that some MPI-IO variables are not using the right precision.

**Comment by tgastine** [comment]
In between, I suggest you use simple precision for the output G files.

**Comment by lakecity** [comment]
Thanks! Single precision works fine for me. To the moment it's qite enough for me and I can proceed further. But anyway the python's reader still gives error " buffer is too small for requested array". I used the grid used in one of the samples. May be it has sence to exclude it at all.

**Comment by tgastine** [comment]
I just had a look into it. There was indeed a problem with the header writing with MPI-IO: displacements were not correctly handled when double precision was requested. I just push a fix, just update the code in case you want to use double precision G files: c6fc7dad8b8bbaf3f99caba917baa9256c55e52d

**Comment by lakecity** [comment]
thanks!
