### ISSUE TITLE
MagicCoeffCmb does not work with ave=True

### ISSUE THREAD

**Issue by lakecity** [magic-sph/magic#19]
Hi! 

MagicCoeffCmb does not work with ave=True:

>cmb = MagicCoeffCmb(precision=np.float64,tag=2,ave=True)

Reading ./B_coeff_cmb_ave.2

ValueError                                Traceback (most recent call last)
<ipython-input-18-13739854396a> in <module>()
----> 1 cmb = MagicCoeffCmb(precision=np.float64,tag=2,ave=True)

/home/mr/Work/2019/magic/python/magic/coeff.pyc in __init__(self, tag, datadir, ratio_cmb_surface, scale_b, iplot, lCut, precision, ave, sv, quiet)
    173             while 1:
    174                 try:
--> 175                     data.append(f.fort_read(precision))
    176                 except TypeError:
    177                     break

/home/mr/Work/2019/magic/python/magic/npfile.pyc in fort_read(self, dt, shape, endian, order, head_size)
    307                                                      known_dimensions_size)
    308             if illegal:
--> 309                 raise ValueError("unknown dimension doesn't match record size")
    310             shape[shape.index(-1)] = unknown_dimension_size
    311         else:

ValueError: unknown dimension doesn't match record size

>ls -lh B_coeff_cmb_ave.2
-rw-rw-r-- 1 mr mr 3,1M окт 23 19:17 B_coeff_cmb_ave.2

Thanks.

**Comment by tgastine** [comment]
I can't reproduce your bug. I just tried reading a cmb ave file produced in the sample testCoeffOutputs and this work perfectly fine. I guess your problem might rather come from the tag you're passing: it should be a character string not an integer, so try passing tag='2' to MagicCoeffCmb instead of tag=2.

**Comment by lakecity** [comment]
sorry for delay: I missed the letter from the site.  For me testCoeffOutputs gives the same: 
from magic import *
 cmb = MagicCoeffCmb(tag='start') works, but 
cmb = MagicCoeffCmb(tag='start',ave=True)
Reading ./B_coeff_cmb_ave.start
AttributeError: MagicCoeffCmb instance has no attribute 'ElM' at line 334 of coeff.py.  
and ElM is realy defined in the block "if not ave"???

**Comment by tgastine** [comment]
Oh I see now, this occurs in the plotting routine. Try with iplot=False for now, this should work fine.

**Comment by lakecity** [comment]
OK. Thank you!
