### ISSUE TITLE
A question about Poincaré number

### ISSUE THREAD

**Issue by JWDei** [magic-sph/magic#20]
Based on the paper _Scale variability in convection-driven MHD dynamos at low Ekman number_ and the file input.nml in directory magic-master/samples/dynamo_benchmark, ra = 1.5D6, ek = 2.0D-4, nVarDiff = 4, pr = 1.0D0 and prmag = 2.0D0 are set, the simulation result in ten time scales (n_tScale = 0) is indeed a Earth-like geodynamo. But when Poincaré number (po = -1.05D-7, according to the reality of the earth) is added  input.nml, the simulated magnetic field will decay rapidly in the first time scales. But in theory, the addition of this item should not produce such a drastic change in such a short time. Similarly, changing the Rayleigh Numbers above to 1.75D6, 2.0D6, and 2.5D6 gives similar results. Considering that precession is not explained in detail in the magic manual, so I want to ask if the code for the precession term is complete or exits another problems.

**Comment by AnkitBarik** [comment]
That is a bit strange. The code for precession is certainly correct and has been benchmarked. I will try simulating your setup and get back to you.

**Comment by JWDei** [comment]
> That is a bit strange. The code for precession is certainly correct and has been benchmarked. I will try simulating your setup and get back to you.

Could you please tell me in which benchmark did you test precession. And whether the from of the Navier-Stokes equation with precession in the Boussinesq limit is that in the following photo (ep is the direction of precession): 
<img width="623" alt="QQ20191211-0" src="https://user-images.githubusercontent.com/45089101/70604086-ec805f80-1c32-11ea-834b-284ec0c98f04.png">
