### ISSUE TITLE
Questions about nRotIC

### ISSUE THREAD

**Issue by JWDei** [magic-sph/magic#22]
I'm really sorry that I didn't raise all the relevant questions last time. I would like to ask what are the units of columns 2, 3 and 4 in rot.TAG. After adding "kbotb=3, sigma_ratio=1.D0, nRotIC=1," to the benchmark from _dynamo_benchmark_, I checked the rot.TAG file and found that the rotation rate of inner core was so huge and even up to the amazing value of 76. If the unit of this rotation rate is also rad/time scale, is this value normal?

**Comment by tgastine** [comment]
This is hard to say whether the value is normal or not it depends on the setup you are looking at.
