### ISSUE TITLE
problem with concatenation in MagicTs

### ISSUE THREAD

**Issue by lakecity** [magic-sph/magic#23]
Hi! 

There is a problem with concatenation of two long files in MagicTs:

MagicTs(field='e_kin',tag='1')      ==> Figure_1
MagicTs(field='e_kin',tag='2')      ==> Figure_2
MagicTs(field='e_kin',tag='[1,2]') ==> Figure_3

The time of the last checkpoint in log.1 corresponds to the end time in e_kin.1 and start in e_kin.2.

wc -l e_kin.1  ==> 26554
wc -l e_kin.2  ==> 26379

May be it is overflow? I used sngl precision output. Each run is 24hs.

For short time series it is OK. 

I can provide the link to the data.

![Figure_1](https://user-images.githubusercontent.com/10127514/72527115-14d62c00-3879-11ea-9aac-d214b5de2ff5.png)
![Figure_2](https://user-images.githubusercontent.com/10127514/72527129-1acc0d00-3879-11ea-82d0-ca739ca7e88f.png)
![Figure_3](https://user-images.githubusercontent.com/10127514/72527135-1f90c100-3879-11ea-96a7-254a6a7947e4.png)

**Comment by tgastine** [comment]
As far as I can see what happened is that the concatenation took first the tag='2' and then the tag='1'. Since it uses access time to determine the ordering to concatenate the files, this likely means that your tag='1' files have been touched/accessed more recently than the others. To fix it you can simply touch the files in the working directory:

```sh
> touch *.1
> touch *.2
```

This should fix it.

**Comment by lakecity** [comment]
Thank you! It works! Usualy I make long simulations at the server and then copy it to the local pc. The order how it make copy is unpredictable ;) It was also suspicious for me:
! Storing checkpoint file:
 107798              at time=    2.1833380460E+00
 107799             step no.=             -1                    !!!!!!!!!!!!!!!!!!!!
 107800            into file=checkpoint_ave.7 
Thanks!

**Comment by tgastine** [comment]
You can try using rsync instead of scp it should maintain the access time of the files.
