### ISSUE TITLE
Unknown error when running program

### ISSUE THREAD

**Issue by ghost** [magic-sph/magic#33]
Trying out the boussBenchSat program with some modified parameters, and I run into an error when executing magic.exe:

 ! Something went wrong, MagIC will stop now
 ! See below the error message:

 ! Singular Matrix ps0Mat in ps_cond!

**Comment by AnkitBarik** [comment]
Hi, could you please paste your input namelist?

**Comment by ghost** [comment]
&grid
 n_r_max     =33,
 n_cheb_max  =31,
 n_phi_tot   =160,
 n_r_ic_max  =17,
n_cheb_ic_max=15,
 minc        =1,
 nalias      =20,
/
&control
 mode        =1,
 tag         ="test",
 n_time_steps=500000,
 courfac     =2.5D0,
 alffac      =1.0D0,
 dtmax       =1.0D-4,
 alpha       =0.6D0,
 runHours    =12,
 runMinutes  =00,
 tEND        =1.5d0,
/
&phys_param
 ra          =1.d5,
 ek          =1.0D-3,
 pr          =0.d0,
 prmag       =5.0D0
 radratio    =0.35D0,
 ktops       =3,
 kbots       =3,             
/
&start_field
 l_start_file=.false.,
 start_file  ="rst_end.start",
 init_b1     =0,
 amp_b1      =0,
 init_s1     =0404,
 amp_s1      =0.1,
/
&output_control
 dt_log      =0.1,
 n_log_step  =10,
 n_graphs    =0,
 dt_graph    =0.1,
 dt_movie    =0.1,
 n_rsts      =1,
 n_stores    =0,
 runid       ="case 0",
 l_movie     =.true.,
 movie(1)    ="Vall r=0.675",
 movie(2)    ="Temperature r=0.675",
 movie(3)    ="temp Eq",
/
&mantle
 nRotMa      =0
/
&inner_core
 sigma_ratio =0.d0,
 nRotIC      =0,
/

**Comment by AnkitBarik** [comment]
Please set pr to a non-zero value and try again ( 1.0d0 is a commonly used value).

**Comment by ghost** [comment]
That worked. Welp, meant to change prmag to 0, not pr to 0. Guess it really does take another pair of eyes to spot the obvious. Thanks!
