### ISSUE TITLE
Non-dimensional temperature does not show 0 and 1 at boundaries  

### ISSUE THREAD

**Issue by vinaycchndra** [magic-sph/magic#35]
Hello all,
I am trying to simulate a simple convection problem in a spherical shell with constant boundary temperatures where I intend to have 1 at inner boundary and 0 at outer boundary for that I  give s_top = 0 0 0 0 and s_bot = 0 0 1 0  in the input file but it overwrites my inputs and in log file shows: 
!  Const. temp. at outer boundary S =    -3.288591E-01
!  Const. temp. at inner boundary S =      6.711409E-01

**Comment by tgastine** [comment]
Yes this could be. For historical reason the contrast was never set to 0 and 1 but the difference \Delta T is of course 1 which is what matters in your case.
