### ISSUE TITLE
Issue using l_true_time in input.nml file

### ISSUE THREAD

**Issue by ABruneel04** [magic-sph/magic#37]
Hello,

I am attempting to utilize the line l_true_time = .true. in my input.nml file in the hopes of using the movie files created from my run in ParaView. However, when I write that line of code, MagIC says that it does not recognize l_true_time from the namelist and does not begin running. I tried changing l_true_time to false (the default value) to see if it would recognize the command then, but it still did not work. Removing the line from my code entirely works, but defeats the goal of eventually using it in my input.nml. I was wondering if it is possible I am typing the command incorrectly, or if this is a separate issue entirely? I would love any help with this, thank you!

**Comment by tgastine** [comment]
Yes indeed `l_true_time` does not exist any longer since it was not working properly and fairly useless. You don't need such option to convert your movie files to paraview.
