### ISSUE TITLE
The moon's gravity？

### ISSUE THREAD

**Issue by CuspXiao** [magic-sph/magic#41]
Does the current code include lunar gravity? If not, is it possible to add?

**Comment by tgastine** [comment]
I'm not sure what you mean by lunar gravity. Isn't it roughly proportionnal to radius as in Earth's core?

**Comment by CuspXiao** [comment]
> I'm not sure what you mean by lunar gravity. Isn't it roughly proportionnal to radius as in Earth's core?
I mean the geomagnetic field has a clear lunar tide signal, can this code recreate this tidal effect?My expression may not be clear, please forgive me.

**Comment by tgastine** [comment]
This is not directly part of MagIC for now but I think Adrian Barker has publications where he used MagIC with tidal effects.

**Comment by CuspXiao** [comment]
Thanks very much. I get the information  i need.
